import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { Header } from "@/components/layout/Header";
import { Footer } from "@/components/layout/Footer";
import { TransitionProvider } from "@/context/TransitionContext";
import { Suspense } from "react";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const viewport: Viewport = {
  themeColor: "#1a1a1a",
};

export const metadata: Metadata = {
  metadataBase: new URL('https://gk-8.fr'),
  title: {
    template: '%s | GK-8 - Prévention TMS & Dos',
    default: 'GK-8 | La méthode 8 gestes pour sauver votre dos',
  },
  description: "La première méthode de prévention active des TMS et maux de dos conçue pour le terrain. Formation rapide (2h), efficace et adoptée par les pros (BTP, Logistique, Industrie).",
  keywords: ["Prévention TMS", "Mal de dos travail", "Formation gestes et postures", "Sécurité au travail", "GK-8", "Santé sécurité", "BTP", "Logistique"],
  authors: [{ name: "GK-8 by SHOU Edition" }],
  openGraph: {
    title: 'GK-8 | Sauvez votre dos en 8 gestes',
    description: 'La méthode de prévention terrain qui change tout. Rapide, visuelle, efficace.',
    url: 'https://gk-8.fr',
    siteName: 'GK-8',
    images: [
      {
        url: '/og-image.jpg',
        width: 1200,
        height: 630,
        alt: 'GK-8 Méthode de prévention',
      },
    ],
    locale: 'fr_FR',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'GK-8 | Prévention TMS Terrain',
    description: '8 gestes pour une carrière durable. Découvrez la méthode.',
    creator: '@gk8_method',
  },
  icons: {
    icon: '/icon', // generated by icon.tsx
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr" className="dark">
      <body className={`${inter.variable} antialiased min-h-screen bg-gk-black text-gk-white flex flex-col`}>
        <Suspense fallback={null}>
          <TransitionProvider>
            <Header />
            <main className="flex-grow">
              {children}
            </main>
            <Footer />
          </TransitionProvider>
        </Suspense>

        {/* Structured Data for SEO */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "EducationalOrganization",
              "name": "GK-8",
              "url": "https://gk-8.fr",
              "logo": "https://gk-8.fr/icon",
              "description": "Organisme de formation spécialisé dans la prévention des TMS et maux de dos sur le terrain.",
              "sameAs": [
                "https://shou-edition.com"
              ],
              "offers": {
                "@type": "Offer",
                "category": "Formation Professionnelle",
                "name": "Formation Gestes Clés GK-8",
                "description": "Formation présentielle ou visio pour équipes terrain."
              }
            })
          }}
        />
      </body>
    </html>
  );
}
